# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            tomchop
tagline:          'APT-buster. Incident handler, lethal forensicator, wannabe malware reverser. Thoughts are my own.'
url:              "http://tomchop.me"
baseurl:          ""
email:            tomchop@gmail.com
twitter_username: tomchop_
github_username:  tomchop

author:
  name:           'Thomas Chopitea'
  url:            https://twitter.com/tomchop_
