# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Global
timezone: Europe/Paris

# Site settings
title: tomchop[is].me
email: tomchop@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  APT-buster. Incident handler, lethal forensicator, wannabe malware reverser. Thoughts are my own.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tomchop.me" # the base hostname & protocol for your site
twitter_username: tomchop_
github_username:  tomchop

# Build settings
markdown: kramdown
