baseurl      = "https://tomchop.me/"
title        = "tomchop's blog"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "tomchop's musings"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "tomchop's musings"
  keywords = "homepage, blog"
  images = [""]

  enableThemeToggle = true

  customCSS = ["/css/custom.css"]

  [author]
    name = "tomchop"

  [params.footer]
    trademark = false
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by Hugo"
    ]

  [params.portrait]
    path     = "/img/avatar.png"
    alt      = "Portrait"
    maxWidth = "200px"

  [[params.social]]
    name = "github"
    url  = "https://github.com/tomchop"

  [[params.social]]
    name = "mastodon"
    url  = "https://infosec.exchange/tomchop"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/tomchop_"

  [[params.social]]
    name = "keybase"
    url  = "https://keybase.io/tomchop"



[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "DFIR musings"
    subtitle = "simple musings"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark = ">"
      logoText = " ~/"
      logoHomeLink = "/"
      logoCursorPathname = true
      logoCursorAnimate  = "4s"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "projects"
    name       = "Projects"
    url        = "/projects"

  [[menu.main]]
    identifier = "talks"
    name       = "Talks"
    url        = "/talks"
